# Generated by Django 3.2.25 on 2025-12-16 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='自习室名称')),
                ('location', models.CharField(max_length=200, verbose_name='位置')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='图片')),
                ('total_seats', models.IntegerField(default=0, verbose_name='总座位数')),
                ('available_seats', models.IntegerField(default=0, verbose_name='可用座位数')),
                ('open_time', models.TimeField(default='08:00:00', verbose_name='开放时间')),
                ('close_time', models.TimeField(default='22:00:00', verbose_name='关闭时间')),
                ('status', models.CharField(choices=[('open', '开放'), ('closed', '关闭'), ('maintenance', '维护中')], default='open', max_length=20, verbose_name='状态')),
                ('facilities', models.TextField(blank=True, help_text='空调、插座、WiFi等', verbose_name='设备设施')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '自习室',
                'verbose_name_plural': '自习室',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=20, verbose_name='座位号')),
                ('row', models.IntegerField(default=1, verbose_name='行号')),
                ('column', models.IntegerField(default=1, verbose_name='列号')),
                ('status', models.CharField(choices=[('available', '可预约'), ('occupied', '已预约'), ('unavailable', '不可用')], default='available', max_length=20, verbose_name='状态')),
                ('has_power', models.BooleanField(default=True, verbose_name='是否有电源')),
                ('has_lamp', models.BooleanField(default=False, verbose_name='是否有台灯')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.studyroom', verbose_name='所属自习室')),
            ],
            options={
                'verbose_name': '座位',
                'verbose_name_plural': '座位',
                'ordering': ['room', 'seat_number'],
                'unique_together': {('room', 'seat_number')},
            },
        ),
    ]
