# Generated by Django 3.2.25 on 2025-12-16 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='预约日期')),
                ('time_slot', models.CharField(choices=[('morning', '上午 (08:00-12:00)'), ('afternoon', '下午 (13:00-17:00)'), ('evening', '晚上 (18:00-22:00)')], max_length=20, verbose_name='时段')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('completed', '已完成'), ('cancelled', '已取消'), ('expired', '已过期')], default='approved', max_length=20, verbose_name='状态')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.seat', verbose_name='座位')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='预约用户')),
            ],
            options={
                'verbose_name': '预约',
                'verbose_name_plural': '预约',
                'ordering': ['-booking_date', '-created_at'],
                'unique_together': {('seat', 'booking_date', 'time_slot')},
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField(auto_now_add=True, verbose_name='签到时间')),
                ('checkout_time', models.DateTimeField(blank=True, null=True, verbose_name='签退时间')),
                ('duration', models.IntegerField(default=0, verbose_name='使用时长(分钟)')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking', verbose_name='预约')),
            ],
            options={
                'verbose_name': '签到记录',
                'verbose_name_plural': '签到记录',
                'ordering': ['-checkin_time'],
            },
        ),
    ]
